### ISSUE TITLE
设置了 PUID PGID 后文件所有者仍然为root

### ISSUE THREAD

**Issue by solarpowerinncr** [xavier-niu/cloudreve-docker#50]
我的启动命令如下
```
docker run -d \
  --name cloudreve \
  -e PUID=1000 \
  -e PGID=100 \
  -e TZ="Asia/Shanghai" \
  -p 5212:5212 \
  --restart=unless-stopped \
  -v /home/sherry/cloudreve/uploads:/cloudreve/uploads \
  -v /home/sherry/cloudreve/config:/cloudreve/config \
  -v /home/sherry/cloudreve/db:/cloudreve/db \
  -v /home/sherry/cloudreve/avatar:/cloudreve/avatar \
  xavierniu/cloudreve:latest
```
启动后，几个文件夹的所有者为PUID=1000的用户，但是文件夹中的文件所有者还是为root用户

**Comment by justxuewei** [comment]
目前已经移除PUID和PGID，请考虑使用docker提供的`--user`flag配置

**Comment by solarpowerinncr** [comment]
使用user后，如果为非root用户，会出现权限问题

日志如下

```
[Panic]   2021-08-29 16:59:02 无法创建配置文件, open /cloudreve/config/conf.ini: permission denied
panic: 无法创建配置文件, open /cloudreve/config/conf.ini: permission denied

goroutine 1 [running]:
github.com/cloudreve/Cloudreve/v3/pkg/util.(*Logger).Panic(0xc0000c21e0, 0x11eb2ec, 0x1c, 0xc00021fab0, 0x1, 0x1)
        /ProjectCloudreve/Cloudreve/pkg/util/logger.go:74 +0xe5
github.com/cloudreve/Cloudreve/v3/pkg/conf.Init(0x7fffd3dfdf15, 0x1a)
        /ProjectCloudreve/Cloudreve/pkg/conf/conf.go:108 +0xc36
github.com/cloudreve/Cloudreve/v3/bootstrap.Init(0x7fffd3dfdf15, 0x1a)
        /ProjectCloudreve/Cloudreve/bootstrap/init.go:18 +0x3e
main.init.0()
        /ProjectCloudreve/Cloudreve/main.go:23 +0x205
```

我的启动命令如下
```
docker run -d \
  --name cloudreve \
  -e TZ="Asia/Shanghai" \
  -p 5212:5212 \
  --user 1000:100 \
  --restart=unless-stopped \
  -v /home/sherry/cloudreve/uploads:/cloudreve/uploads \
  -v /home/sherry/cloudreve/config:/cloudreve/config \
  -v /home/sherry/cloudreve/db:/cloudreve/db \
  -v /home/sherry/cloudreve/avatar:/cloudreve/avatar \
  xavierniu/cloudreve:latest
```

**Comment by justxuewei** [comment]
你的`/cloudreve/config/conf.ini`的权限是user吗？
